### ISSUE TITLE
FF 133 broke tabs_on_bottom.css

### ISSUE THREAD

**Issue by CurePindal** [MrOtherGuy/firefox-csshacks#456] opened 2024-11-27 12:19 UTC
tabs_on_bottom.css is no longer working in FF 133.

edit: sorr, noticed too late its reported here:
https://github.com/MrOtherGuy/firefox-csshacks/issues/438

**Comment by artemlive** [comment] 2024-11-27 12:20
It's the same to me.

**Comment by madeddy** [comment] 2024-11-27 12:23
Did you also try _tabs_on_bottom_v2.css_ ?

**Comment by artemlive** [comment] 2024-11-27 12:32
@madeddy I tried and it doesn't work. 
And there is another [report.](https://github.com/MrOtherGuy/firefox-csshacks/issues/438#issuecomment-2503708490)

**Comment by Laephis** [comment] 2024-11-28 02:11
Also tried tabs_on_bottom_v2.css, FF 133 on Linux, and not working for me as well.

**Comment by mfrumento** [comment] 2024-11-30 01:36
Any fix?

**Comment by MrOtherGuy** [comment] 2024-11-30 02:04
> Any fix?

Yes, use tabs_on_bottom_v2.css instead.

I'm closing this as duplicate of 438.

**Closed by MrOtherGuy** 2024-11-30 02:04 UTC
