### ISSUE TITLE
compact_urlbar_megabar.css applies wrong padding to #identity-box on Firefox protected pages

### ISSUE THREAD

**Issue by TheFineBroccoli** [MrOtherGuy/firefox-csshacks#81] opened 2020-10-21 11:20 UTC
Hi! I noticed that the padding applied to `#identity-box` is broken on protected pages

![broken](https://user-images.githubusercontent.com/46381898/96712558-9ece9a80-139f-11eb-9a9b-361c248bda14.png)

Removing/commenting out this rule fixes the issue 
https://github.com/MrOtherGuy/firefox-csshacks/blob/5e823bafd54a966558837f7977bee1a3bc74948a/chrome/compact_urlbar_megabar.css#L17

![normal](https://user-images.githubusercontent.com/46381898/96712770-e9501700-139f-11eb-932e-c3b0055ae7e3.png)

~~And nothing else seems to be broken when it's removed.~~

Just found that it breaks the height of `#urlbar-input-container`, could there be a way around this?

Firefox 81.0.2, Linux

**Comment by MrOtherGuy** [comment] 2020-10-21 12:05
Can you check if that happens on other non-http(s) pages too? Like extension pages or file:// uri?

**Comment by MrOtherGuy** [comment] 2020-10-21 12:12
I think chances are it's wrong whenever the identity has some label in text.

**Comment by MrOtherGuy** [comment] 2020-10-21 12:59
Actually that padding was added specifically for the purpose to prevent such offsets from happening. But I guess internal style has changed since so I can just remove that padding rule altogether - that's always nice.

Fixed in #16a4cd3d5bb43c811209da9ffe49f90a4118e66c

**Comment by TheFineBroccoli** [comment] 2020-10-21 14:04
@MrOtherGuy Sorry for not getting back to you sooner, I did some testing and it turns out that the padding wasn't really unnecessary. It's only needed when the `#urlbar` is in focused state, but it's too big for protected pages, so I added these two lines (instead of the `#identity-box{ padding-block: var(--urlbar-icon-padding) }`):

```css
#urlbar[focused="true"] #identity-box{ padding-block: var(--urlbar-icon-padding) !important; }
#urlbar[focused="true"] #identity-box[pageproxystate="valid"]{ padding-block: calc(var(--urlbar-icon-padding) / 2) !important; }
```
And everything seems to work as expected, without any weird height shifting as it did without the padding

**Comment by MrOtherGuy** [comment] 2020-10-21 14:17
Hmm. Exactly when is it still necessary and how does it manifest? (I mean *without* that padding)

I tested with Firefox 82 and 84 lots of combinations of pages in normal & compact densities and I couldn't reproduce the original problem that required me to add that padding in the first place. Granted I only tested on Windows10 and I could have missed the specific case.

**Comment by TheFineBroccoli** [comment] 2020-10-21 15:27
Here are few more screenshots without the padding applied:

Unfocused url-bar

![unfocused-urlbar](https://user-images.githubusercontent.com/46381898/96740937-9ab37480-13c1-11eb-8451-70e8368413ba.png)

Focused urlbar

![focused-urlbar](https://user-images.githubusercontent.com/46381898/96740775-6fc92080-13c1-11eb-870c-c04b07452cf4.png)

Focused urlbar with text

![focused-urlbar-with-text](https://user-images.githubusercontent.com/46381898/96740931-98e9b100-13c1-11eb-8070-4791042fd6fd.png)

Protected webpage unfocused urlbar

![protected-webpage-unfocused-urlbar](https://user-images.githubusercontent.com/46381898/96740934-9a1ade00-13c1-11eb-966f-d9e92187da45.png)

Protected webpage focused urlbar

![protected-webpage-focused-urlbar](https://user-images.githubusercontent.com/46381898/96740933-99824780-13c1-11eb-8353-b4772b0d5888.png)

As you can see the input area gets smaller on focus, the padding applied to `#identity-box` prevents it, but for some reason it's too big for the "badge" on protected webpages

**Comment by MrOtherGuy** [comment] 2020-10-21 16:02
All right, thanks for that. Now I know what happens and I'm gonna explain a bit so that I remember in the future. The extra padding is there to fix a problem where `#urlbar-input-container` collapses too much if

1. The dropdown is shown when urlbar is clicked and
2.  urlbar text-field is empty

It does not happen if one has unchecked "Top Sites" from being included in urlbar results which makes the drop-down not be shown on-click. Thus there will never be a scenario where urlbar is both emtpy and dropdown is being shown.

Further, the original fix by adding more padding to identity-box appears to work without issues *except* in compact mode. This happens because the label text is too taller than the icon and the padding value expects the size of the icon.

So, what we need to do is to indeed apply the original padding but not to the identity-box but to the identity icon. But adding it as padding would make the icon squished so add it as margin instead.

So please try adding `#identity-icon{ margin-block: var(--urlbar-icon-padding) } ` and see if you can spot any issues.

**Comment by TheFineBroccoli** [comment] 2020-10-21 16:20
Yep that seems to do the trick, I haven't noticed anything. Thank you!

**Comment by MrOtherGuy** [comment] 2020-10-21 19:33
I've pushed that as a fix for this issue. 
Thanks for letting me know of the problem and testing.

**Closed by MrOtherGuy** 2020-10-21 19:33 UTC

**Comment by TheFineBroccoli** [comment] 2020-10-22 12:13
No problem!
