### ISSUE TITLE
Firefox 133:  Tabs-on-bottom is broken

### ISSUE THREAD

**Issue by UnixRonin** [MrOtherGuy/firefox-csshacks#468] opened 2024-11-30 02:51 UTC
Just a quick note to add to the list of Firefox 133 problems that 133 appears to have broken tabs-on-bottom.
(Yes, _again_.  It's almost like it's deliberate.)

**Comment by MrOtherGuy** [comment] 2024-11-30 03:37
This is a duplicate of #438 - tabs_on_bottom.css is deprecated, just use tabs_on_bottom_v2.css instead.

**Closed** 2024-11-30 03:37 UTC
