### ISSUE TITLE
overlay_fullscreen_toolbars.css do nothing for me :(

### ISSUE THREAD

**Issue by vitaly-zdanevich** [MrOtherGuy/firefox-csshacks#367] opened 2024-05-15 19:19 UTC
macOS, current stable Firefox.

**Comment by MrOtherGuy** [comment] 2024-05-16 02:25
Yeah, it (and bunch of other styles were outdated for fullscreen specific rules, but they should be fixed now. Thanks for reporting!

**Closed by MrOtherGuy** 2024-05-16 02:25 UTC

**Comment by vitaly-zdanevich** [comment] 2024-05-17 02:30
Thanks, now it works, and it COOL! This is good for performance on my old laptop. Maybe you should propose that CSS to Mozilla, to have such checkbox in Preferences?

**Comment by MrOtherGuy** [comment] 2024-05-17 03:18
If the fullscreen toolbar behavior was changed it would certainly not be done with code like this - we just need to use this kind of "override styling" because aside from building Firefox from source we can't properly change the implementation and userChrome.css is best we got.

If you care about this sort of overlay behavior then I suggest you open a new ticket on [bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?) or maybe [connect.mozilla.org](https://connect.mozilla.org/t5/ideas/idb-p/ideas) proposing such a feature.

**Comment by vitaly-zdanevich** [comment] 2024-05-17 03:48
Thanks, created https://connect.mozilla.org/t5/ideas/fullscreen-please-add-overlay-toolbar-like-in-safari/idi-p/57351#M33573

**Comment by vitaly-zdanevich** [comment] 2024-05-17 21:04
Is it possible to hide the toolbar _always_ when the mouse in not on the top?

https://github.com/MrOtherGuy/firefox-csshacks/assets/3514015/3a3d34bc-9c96-4e1b-b9ac-2532be50d915

**Comment by MrOtherGuy** [comment] 2024-05-18 02:21
I don't really understand what''s going on threre to be honest. There's supposed to be a 600ms delay before the toolbars get hidden [from this](https://github.com/MrOtherGuy/firefox-csshacks/blob/31cb27a5d8e11a4f35499ea9d75cc9939399d915/chrome/overlay_fullscreen_toolbars.css#L11) but that doesn't really match the recording.

Unfortunately whatever the cause, it sounds like macOS specific issue and I can't help you with that.

**Comment by vitaly-zdanevich** [comment] 2024-05-21 06:58
I removed this line with delay, I do not like animations.

**Comment by MrOtherGuy** [comment] 2024-05-21 09:28
Don't remove the whole thing. If you don't want an animation then just make the duration part (`100ms`) be zero (`0sm`). Then then animation should be instant, but still transitioned with 600ms delay.
