### ISSUE TITLE
Black box (bookmarks) on pre-load page

### ISSUE THREAD

**Issue by jacksongoode** [MrOtherGuy/firefox-csshacks#104] opened 2021-05-02 04:08 UTC
On Ubuntu, FF88 with bookmarks bar disabled. This css seems to work on Windows. So, it could be an issue with Linux?
I'm using [this](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_bookmarks_and_main_toolbars.css) file.

Here's a photo of the issue that appears in a flash before a page fully loads.
![Screenshot from 2021-05-01 21-06-06](https://user-images.githubusercontent.com/54308792/116801749-62ec5e80-aac1-11eb-8e9c-c7e4da6588b0.png)

**Comment by MrOtherGuy** [comment] 2021-05-02 07:20
You say that this happens "on pre-load page" so does that mean it shows blank briefly when browser is starting up, but then starts to work normally?

If so, then this might just be intentional and the only reason why you don't see that on windows is because session restore is much faster on your Windows system.

There is an intentional delay on startup that achieves two things: 1. So that Firefox computes some urlbar related things properly and 2. so that Firefox restores bookmarks toolbar content more reliably.

**Comment by jacksongoode** [comment] 2021-05-02 07:23
No, this appears on every new tab that is loaded.

**Comment by MrOtherGuy** [comment] 2021-05-02 07:42
Oh, okay. But that sounds kinda weird, I can't really guess what's going on there. I tried this on my Fedora system, and I can't seem to replicate the problem. As far as I can tell, the behavior looks exactly the same as with Windows10. Do you have some other styles that could be causing some incompatiblities?

**Comment by jacksongoode** [comment] 2021-05-02 08:40
Nothing within Firefox's userChrome. I think it happens when a new window is expecting the navbar/bookmarks bar to be present but it's not and there is this black void behind it for a second.

**Comment by jacksongoode** [comment] 2021-05-02 08:55
Ok, it seems like removing this [line](https://github.com/MrOtherGuy/firefox-csshacks/blob/2505a9693e33f714b2efcee0d26762a773a299e5/chrome/autohide_bookmarks_and_main_toolbars.css#L29) allows the black bar to stick, even though the navbar auto-hides.

**Comment by MrOtherGuy** [comment] 2021-05-02 08:58
Well that would do it certainly. The purpose of that line is to move web content upwawrds to fill the space where toolbars would have been.

**Comment by jacksongoode** [comment] 2021-05-02 09:07
Yeah, for whatever reason (especially on startup), this black bar appears under the nav/bookmarks bar until a page loads.

**Comment by MrOtherGuy** [comment] 2021-05-02 09:08
Right but why are you removing that line ?

**Comment by jacksongoode** [comment] 2021-05-02 09:10
> Right but why are you removing that line ?

It was just to see what the culprit might be. I went through and commented out a lot of the lines to find out why this is happening but to not avail. Interestingly, your code [here](https://raw.githubusercontent.com/MrOtherGuy/firefox-csshacks/master/chrome/autohide_toolbox.css) does not experience the same issue.

**Comment by MrOtherGuy** [comment] 2021-05-02 09:20
> Ok, it seems like removing this line allows the black bar to stick, even though the navbar auto-hides. Maybe it has something to do with the sessionrestored state?

I'm a bit confused then. That comment suggests to me that the issue was **caused** by you removing that line and it gets fixed by adding that back. I take it it's really the other way round?

I still can't reproduce the problem, but I guess you could try adding `!important` to that rule at line 29 and see if it works out for you. I don't understand why you would need it, but it's somewhat plausible that it would work here.

**Comment by jacksongoode** [comment] 2021-05-02 09:31
> > Ok, it seems like removing this line allows the black bar to stick, even though the navbar auto-hides. Maybe it has something to do with the sessionrestored state?
> 
> I'm a bit confused then. That comment suggests to me that the issue was **caused** by you removing that line and it gets fixed by adding that back. I take it it's really the other way round?
> 
> I still can't reproduce the problem, but I guess you could try adding `!important` to that rule at line 29 and see if it works out for you. I don't understand why you would need it, but it's somewhat plausible that it would work here.

Sorry, I should be clear. The original css and nothing else causes this issue with the black box appearing before a page load. It may be a Linux particular thing relating to the lack of content on a page prior to load?

**Comment by MrOtherGuy** [comment] 2021-05-02 11:13
> Update: I tried it on FF89b, and it works perfectly. Not sure what the issue is. Bizarre.

Oh. Well that's interesting, thanks for letting me know. In that case I'm not going to research this any further. I know it has other small problems with the upcoming proton styling but those are things I know how to fix.

**Closed** 2021-06-03 06:55 UTC
