### ISSUE TITLE
multirow-tabs  on firefox 107.0beta1 don't grow tab rows correctly

### ISSUE THREAD

**Issue by io-default** [MrOtherGuy/firefox-csshacks#215] opened 2022-10-18 14:04 UTC
For each tab opened 1 more tab row is displayed in Firefox 107 beta1.

e.g. 1 Tab open = 2 Rows displayed while the second on  is empty. 

3Tabs = 4rows etc, until the maximum number of rows is reached as specified in the css (bound by calculated max-height).

**Comment by MrOtherGuy** [comment] 2022-10-18 14:25
Could you take a screenshot of what you are seeing?

**Comment by io-default** [comment] 2022-10-18 14:27
Here: https://i.imgur.com/wkM7PG8.png

**Comment by io-default** [comment] 2022-10-18 14:30
With:
--multirow-n-rows: 6;
 --multirow-tab-min-width: 100px;
 --multirow-tab-dynamic-width: 0;

**Comment by MrOtherGuy** [comment] 2022-10-18 14:53
Thanks, that certainly looks interesting. I'll see what I can do. 

I have some ideas about what could be going on but it has failed quite spectacularly so I can't say anything for certain yet. Thanks for reporting though.

**Comment by MrOtherGuy** [comment] 2022-10-18 20:58
For the record, multi-row_tabs.css seems to work just fine in Nightly 108 but the behavior in 107 is indeed very odd.

I have a hunch this is related to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1790616) somehow or one of its related bugs. Perhaps some change happened in 107 "partially" which leads to incorrect behavior but which has since been fixed in 108?

Currently I have no clue how this should be fixed for 107 as the layout doesn't make any sense to me.

**Comment by io-default** [comment] 2022-10-18 21:01
Ok, thank you for looking into it. I suppose since its still early beta, might as well wait and see : )

**Comment by MrOtherGuy** [comment] 2022-10-19 06:21
I kinda think this is probably unfixable and I doubt the behavior will be change in 107 cycle. 

However, you can go to about:config and set `layout.css.moz-box-flexbox-emulation.enabled` to `true` and the style should work properly afterwards.

Doing that might have some *other* unforeseen consequences though.

**Comment by crestcere** [comment] 2022-10-19 06:42
> I kinda think this is probably unfixable and I doubt the behavior will be change in 107 cycle.
> 
> However, you can go to about:config and set `layout.css.moz-box-flexbox-emulation.enabled` to `true` and the style should work properly afterwards.
> 
> Doing that might have some _other_ unforeseen consequences though.

It disables multirow tabbar and breaks multirow bookmarks

**Comment by io-default** [comment] 2022-10-19 06:48
> It disables multirow tabbar and breaks multirow bookmarks
The option works for me; at least for tabs,  didn't test multi-row bookmarks. Haven't noticed any artifacts yet. (107b2/linux)

**Comment by MrOtherGuy** [comment] 2022-10-19 06:54
With the mentioned pref set, both multi-row_tabs.css and multi-row_bookmarks.css seem to work fine with 107b2 on my system (Win10).

**Comment by crestcere** [comment] 2022-10-19 07:11
> With the mentioned pref set, both multi-row_tabs.css and multi-row_bookmarks.css seem to work fine with 107b2 on my system (Win10).

My bad, I misunderstood. With autohide bookmark toolbar, toolbar breaks as seen in image below.
![Snipaste_2022-10-19_10-03-48](https://user-images.githubusercontent.com/31207969/196620788-071a48cf-aaf7-4f21-87f9-158fa5d4390b.png)

**Comment by MrOtherGuy** [comment] 2022-10-19 07:13
@crestcere That's probably more because you have done something to move tabs below other toolbars - not because of multi-row_bookmarks.css

**Comment by crestcere** [comment] 2022-10-19 07:17
> @crestcere That's probably more because you have done something to move tabs below other toolbars - not because of multi-row_bookmarks.css

You were right, I enabled compatibility option in autohidebookmarks.css but disabling with that it creates empty bar in below address bar

![Snipaste_2022-10-19_10-17-42](https://user-images.githubusercontent.com/31207969/196622742-a18c65f2-1b4a-4137-8f03-b125150e086f.png)

**Comment by MrOtherGuy** [comment] 2022-10-19 07:25
Yeah, I see, multi-row_bookmarks.css + autohide_bookmarks_toolbar.css is problematic combination. I'll see what I can do.

**Comment by MrOtherGuy** [comment] 2022-10-19 08:25
Alright, I was able to make the multi-row_bookmarks.css + autohide_bookmarks_toolbar.css  compatibility rules work in b958b75.

During 107 cycle, it seems you still need to set the earlier mentioned pref to true for this to work. I mean, multi-row_bookmarks.css and multi-row_tabs.css won't work correctly without it in the first place.

**Comment by crestcere** [comment] 2022-10-19 08:45
It's working great. Thank you 😊

**Comment by pgorod** [comment] 2022-11-25 11:11
I'm not sure this is the same thing, but for me the problem with FF 107 (not the beta, the official release which is out now) there was (constant) extra space below the last tab row, and I fixed it with the solution provided here:

https://support.mozilla.org/en-US/questions/1397107

Which is to change this:

```
tabbrowser-tabs { 
   min-height: unset !important;
   padding-inline-start: 0px !important
}
```

to this: 

```
tabbrowser-tabs { 
   height: var(--tab-min-height);
   padding-inline-start: 0px !important
}
```
I don't understand this enough to know what I'm doing. Does this make sense? It works for me...

**Comment by MrOtherGuy** [comment] 2022-11-25 11:36
@pgorod The problem with that is that it breaks the style for Firefox 108 onwards. As far as I know, multi-row_tabs.css doesn't need any changes for 108 and 109, it's only 107 that is not working and would need different CSS like what you linked or by setting the pref mentioned above.

**Comment by pgorod** [comment] 2022-11-25 11:47
Ok, so if I'm reading you correctly, I could just wait (since I'm not on any Beta release channel) for 108 to come out as a regular release, revert that change, and have Multirow tabs working fine again, is that it?

Thanks

**Comment by MrOtherGuy** [comment] 2022-11-25 11:51
Yes, that should be correct.

**Comment by MrOtherGuy** [comment] 2022-11-28 21:55
FYI everybody, AMS777 managed to find a solution in a0a477c for multi-row_tabs.css that works in Firefox 107, 108 and 109.

So, you'll probably want to reset that `layout.css.moz-box-flexbox-emulation.enabled` back to false unless you are also using multi-row_bookmarks.css which is still broken in 107 without that pref.

Still, the issue is now effectively fixed so I'll be closing this.

**Closed by MrOtherGuy** 2022-11-28 21:55 UTC
