### ISSUE TITLE
Multirow tabs do not resize

### ISSUE THREAD

**Issue by AGCaesar** [MrOtherGuy/firefox-csshacks#225] opened 2022-11-16 09:53 UTC
I've just updated Firefox from 106 to 107
I have  am using only multi-row_tabs.css

The area for tabs stopped resizing to the amount of tabs and uses lots of blank space, see screenshot
![20221116104843_window](https://user-images.githubusercontent.com/7844066/202148013-614cc3dc-82b9-4495-bf27-93f112a2b03c.png)

The grey area under the two tabs should not be there. Thank you for your great work!

**Comment by MrOtherGuy** [comment] 2022-11-16 09:58
This is duplicate of #215, see [this comment](https://github.com/MrOtherGuy/firefox-csshacks/issues/215#issuecomment-1283490393)

**Comment by AGCaesar** [comment] 2022-11-16 10:01
Sorry, i forgot the betas. Works perfectly with your fix, thank you!

**Closed** 2022-11-16 10:04 UTC

**Comment by MrOtherGuy** [comment] 2022-11-16 10:05
No problem. Kinda unfortunate that it's not fixable in 107 without the pref but it works at least. You shouldn't need the pref in 108 though.
