### ISSUE TITLE
fake_statusbar_w_bookmarksbar.css -- question

### ISSUE THREAD

**Issue by refriedfood** [MrOtherGuy/firefox-csshacks#244] opened 2022-12-29 08:40 UTC
Is it possible to simply carry over the background of the current url display at the bottom, have it not fade, and shortened the scrollbar? I don't understand the need for the toolbar, nor can I get it to work without being opaque (no matter what I change).

**Comment by MrOtherGuy** [comment] 2022-12-29 08:58
Sorry, but I don't understand what you are asking. The style you mention does require some setup, please refer to [lines 4-11 to set it up.](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/fake_statusbar_w_bookmarksbar.css#L4-L11)

**Comment by refriedfood** [comment] 2022-12-29 10:25
Okay. Without using your config, I'm asking if whether or not it is possible to simply 100% the background of the url hover (which is white) in css, and shorten the scrollbar, instead of having to use the bookmarks toolbar with your config (which does not work for me).

I'm not sure how else I can't explain this as it makes sense to me. Whether or not it can be done is another matter. And if it cannot be done, how could i fix yours to not be opaque?

**Comment by MrOtherGuy** [comment] 2022-12-29 10:37
It would help if you could show a image how you would like things to look.

Some questions:

What do you mean by "simply 100% the background of the url hover"? I just really can't figure out what that means. 

What do you mean by "shortening the scrollbar"? I don't see what relevance that has with statusbar - fake or otherwise.

What do you intend to achieve with non-opaque version of the style in question? I mean, what do you want to be seen through it?

**Comment by refriedfood** [comment] 2022-12-29 14:45
I'm sorry, I didn't add the word _not_ before opaque. What that was regarding was your current tweak as is. No matter what I did, the url was opaque/transparent, regardless of how I tweaked the css. I simply could not see the black text url over your status bar--it constantly renders the page behind it or discolored.

What I was wondering if it was possible was like this:

before: https://images2.imgbox.com/73/cf/Yx2SEYOT_o.png

after: https://images2.imgbox.com/5f/07/SoAmt5KK_o.png

As you can see, all I did was maximize the background box of the url text and shorten the height of the scrollbar. And if the bg box never disappears, then that's the perfect statusbar. Or is that not possible?

**Comment by MrOtherGuy** [comment] 2022-12-29 14:51
Okay I get what you mean now. But the thing is, it is *supposed* to look sort of how you want it to (just a bit taller). You should not see the page behind it, this "fake statusbar" should be completely below the web-content area.

If that is not the case, then my first guess would be that you also have some other styles which are causing this style to not work like it is supposed to.

**Comment by refriedfood** [comment] 2022-12-30 07:37
There wasn't any pre-existing css until I specified colors for the text, or at least tried to.

I see that it has since changed to use the menu bar, which I do not have any interest in. The bookmarks toolbar at the bottom was manageable, but it just needed its background to not be transparent/opalescent when the url was displayed over it. But seeing as I prefer my menu bar at the top, and to have the status bar separate, I don't think this will work any longer.

**Comment by MrOtherGuy** [comment] 2022-12-30 07:47
Note that there are two separate styles in the repository; one which creates fake statusbar by using menubar and another that uses bookmarks toolbar.

Please remove everything else from you userChrome.css and make only include content from fake_statusbar_w_bookmarksbar.css (backup your existing userChrome.css content first if you wish). Don't edit it in any way. Then share a screenshot what it looks like on your system. Maybe we can then figure out what goes wrong.

**Comment by refriedfood** [comment] 2022-12-30 08:00
Sure. Here is the default: 

* https://streamable.com/x6ddon

* https://images2.imgbox.com/4d/8a/vOSzTqhQ_o.png

Done seems to be off by a few pixels.

**Comment by MrOtherGuy** [comment] 2022-12-30 09:04
Your screenshot look about right, although it's less tall it should be (probably caused by you not adding any buttons to that statusbar, but that I could likely fix) 

But I'm not sure what I'm looking at the screen recordings. Neither of them seem to show the statusbar area at all.

**Comment by refriedfood** [comment] 2022-12-30 12:37
Down at the very bottom in teh video, you can't miss it. I'm hovering over links to show you displacement, etc. And I think the bar needs to be smaller height, personally. Here is mine currently on 92:

https://images2.imgbox.com/fa/65/BNBUEZJO_o.png

**Comment by MrOtherGuy** [comment] 2022-12-30 14:48
Okay, so apparently the video quality on streamable mobile website is so horrible that the statusbar just looks like a empty white strip which I thought wasn't even part of the window.

In patch [b434a2d](https://github.com/MrOtherGuy/firefox-csshacks/commit/b434a2d9f5f955cb7e5a7aaeb6aaf89900f06800) I was able to fix most (if not all?) issues you mentioned. Addtionally, while debugging I found that the style would have been completely broken when Firefox 109 lands so thanks for bringing this to my attention.

**Comment by refriedfood** [comment] 2022-12-31 02:02
Great. If there is anything else I can help you with, let me know. How would you suggest resizing the actual statusbar height without interfering with your css too much?

**Comment by MrOtherGuy** [comment] 2022-12-31 06:32
You could add this bit after everything else in that file:

```css
:root:not([inFullscreen]) > body{
  --uc-browser-base-padding: 20px !important;
  --uc-statusbar-text-vertical-position: 0px !important;
}
#personal-toolbar-empty-description{ display: none; }
```

**Comment by refriedfood** [comment] 2022-12-31 07:58
That's gorgeous.

**Comment by MrOtherGuy** [comment] 2022-12-31 08:06
Sweet. Yeah, so the only reason why it is so tall by default is because the style is really intended to achieve super old behavior where there was a statusbar below web-content that was more or less just like any other toolbar, so you could add buttons there or whatever.

Unfortunately with CSS we can't really make it "grow automatically" so it would stay small if no buttons are placed there and then grow to accommodate button space. So I've opted to just let it be taller all the time.

But anyway, it sounds like this is now fixed so I'm closing the issue.

**Closed by MrOtherGuy** 2022-12-31 08:06 UTC
