### ISSUE TITLE
Top Row"Bookmarks" become non functional when many Multi Row "Tabs" are opened

### ISSUE THREAD

**Issue by MrBeavers1** [MrOtherGuy/firefox-csshacks#247] opened 2023-01-16 19:12 UTC
1.) When FireFox 109 toolbar is set to "Compact" density the top row of Multi-Row Bookmarks becomes non functional when many Multi Row "Tabs" are opened at the same time. This seems to happen after a period of some time and not always just after opening and populating multiple "Tab" rows. After closing several multi row "tabs" to reduce tabs back to a single row, the Multi-Row Bookmarks problem persists and does not revert back to normal.

2.) If FireFox toolbar density is set to "Normal", only after hovering over the very bottom edge of a top row bookmark does the bookmark actually highlight and allow a click event. If you move the mouse toward the center of the top row of bookmarks, the bookmarks do not highlight and will not respond to a click event. Also, after closing several multi row "tabs" to reduce tabs back to a single row, the Multi-Row Bookmarks problem persists and does not revert back to normal.

![Mouse only works at Bottom Edge](https://user-images.githubusercontent.com/78175492/212751001-315bb571-9256-46c9-bdc3-68c3ef99fe99.png)

![Mouse does not work when not at bottom edge of Bookmark](https://user-images.githubusercontent.com/78175492/212751143-83f966a2-e756-4d2b-87ab-3a11f396d13c.png)

**Comment by MrOtherGuy** [comment] 2023-01-16 19:17
Could you double check that your styles (multi-row_bookmarks.css and multi-row_tabs.css) are both up to date? This sounds very much like an issue that has been fixed few months ago.

**Comment by MrBeavers1** [comment] 2023-01-16 20:25
We have the latest multi-row_bookmarks.css (Nov 19,  2022). However we are using MultiRowTab-scrollable-autohide.uc.js for the Multi Row Tabs because it allows the tabs to be dragged and dropped. The issue does not appear to be with MultiRowTab-scrollable-autohide.uc.js, only in conjunction with Multi Row Nov 19, 2023  Bookmarks...

**Comment by MrOtherGuy** [comment] 2023-01-17 04:05
I'd suggest you test if you can reproduce the issue without your custom multi-row tabs implementation then. I tried a bunch of things with multi-row_bookmarks.css but was unable to reproduce this.

**Comment by MrBeavers1** [comment] 2023-02-01 18:13
I have identified a way to reliably recreate this issue... 

Turns out the issue is only created when any of the Multi-Row bookmarks are dragged. Even if the dragging lands the bookmark right back where it originated, like dragging the last bookmark then dropping right back where it started.

This causes the top row of bookmarks to only highlight and become functional if your mouse is on the bottom boundary of the bookmark (see pictures below). Moving the mouse closer to the center of the bookmark, the bookmark no longer functions.

If you close FF then re-open, all returns to normal until you attempt to drag and drop any bookmark from within the Multi-Row Bookmarks toolbar again.

![BookMark Boundry Active](https://user-images.githubusercontent.com/78175492/216126869-8740176a-2af6-4fd2-affc-1bbcedb962f8.png)

![BookMark Interior Not Active](https://user-images.githubusercontent.com/78175492/216126943-ef6eeae5-a0e6-425f-8350-a70a439a1c49.png)

 This behavior does not occur if you re-arrange bookmarks from within the FF SideBar.

**Comment by MrOtherGuy** [comment] 2023-02-01 18:22
That sounds *exactly* what would happen in older versions of multi-row_bookmarks.css but it was fixed in commit add8f8c

Are you actually positive the same happen with up-to-date style? I can tell you I cannot reproduce it with the steps you listed.

**Comment by MrBeavers1** [comment] 2023-02-01 18:36
That was it!

Some how this line was truncated
_#PlacesToolbar > hbox:not(_
  display: block;
  width: 80vw;
}

**Updated to:**
#PlacesToolbar > hbox:not(#PlacesToolbarDropIndicatorHolder){ 
  display: block;
  width: 80vw;
}

Now the Bookmarks appear to be working properly.

Thanks for your help!

**Comment by MrOtherGuy** [comment] 2023-02-01 18:38
Cool. Thanks for checking :)

**Closed by MrOtherGuy** 2023-02-01 18:38 UTC
