### ISSUE TITLE
All Bookmark Toolbar items not showing

### ISSUE THREAD

**Issue by jensenkwee** [MrOtherGuy/firefox-csshacks#221] opened 2022-11-12 05:16 UTC
Hi,

This code works for me to render Multi Row Bookmark Toolbar.

However i have 203 bookmarks in my Bookmark Toolbar.

Only the first 96 bookmarks display (including after scroll down overflow).

Are you able to change the code to display ALL bookmarks inside the Bookmarks Toolbar ?

Please can you send me the updated userChrome.css.txt file ?

Thanks so much !

Jensen

[userChrome.css.txt](https://github.com/MrOtherGuy/firefox-csshacks/files/9994158/userChrome.css.txt)

![image](https://user-images.githubusercontent.com/118038207/201458438-525861d1-a661-4fab-af4d-412400f9e02a.png)

![image](https://user-images.githubusercontent.com/118038207/201458459-a13aa09a-eeac-4ff8-b016-df17cb1d59e3.png)

**Comment by MrOtherGuy** [comment] 2022-11-12 05:32
This is essentially a duplicate of #88 - see my comment there for some more info. In short, I don't think this can be fixed with CSS.

**Closed by MrOtherGuy** 2022-11-12 05:32 UTC
